-- MySQL Script generated by MySQL Workbench
-- Wed Dec  6 16:29:38 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Joc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Joc` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Joc` (
  `id` INT NOT NULL,
  `denumire_joc` VARCHAR(45) NULL,
  `data_lansare` VARCHAR(45) NULL,
  `gen` VARCHAR(45) NULL,
  `platforme` VARCHAR(200) NULL,
  `dezvoltator` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Eveniment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Eveniment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Eveniment` (
  `id` INT NOT NULL,
  `denumire` VARCHAR(45) NULL,
  `data` VARCHAR(45) NULL,
  `durata` VARCHAR(45) NULL,
  `id_joc` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `FK_ID_JOC_idx` (`id_joc` ASC),
  CONSTRAINT `FK_ID_JOC`
    FOREIGN KEY (`id_joc`)
    REFERENCES `mydb`.`Joc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Joc`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Joc` (`id`, `denumire_joc`, `data_lansare`, `gen`, `platforme`, `dezvoltator`) VALUES (1, 'Battlefield4', '29.10.2013', 'Strategie, Simulator', 'PlayStation 3, Xbox 360, PlayStation 4, Xbox One, PC (Microsoft Windows)', 'EA Digital Illusions CE');
INSERT INTO `mydb`.`Joc` (`id`, `denumire_joc`, `data_lansare`, `gen`, `platforme`, `dezvoltator`) VALUES (2, 'Kerbal Space Program', '27.04.2015', 'Simulator', 'Mac, Linux, PlayStation 4, Xbox One, PC (Microsoft Windows), Wii U', 'Squad');
INSERT INTO `mydb`.`Joc` (`id`, `denumire_joc`, `data_lansare`, `gen`, `platforme`, `dezvoltator`) VALUES (3, 'Star Wars: The Old Republic', '20.12.2011', 'Joc de rol', 'PC (Microsoft Windows)', 'BioWare Austin');
INSERT INTO `mydb`.`Joc` (`id`, `denumire_joc`, `data_lansare`, `gen`, `platforme`, `dezvoltator`) VALUES (4, 'Minecraft', '7.10.2011', 'Aventura', 'Nintendo Switch, Xbox 360, PlayStation 3, PlayStation 4, Xbox One, PC (Microsoft Windows), Mac, Linux, Android, iOS, PlayStation Vita, Windows Phone, Wii U', 'Mojang AB');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Eveniment`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Eveniment` (`id`, `denumire`, `data`, `durata`, `id_joc`) VALUES (1, 'Grizzle Stream Schedule', '25.08.2016', '11 zile', 1);
INSERT INTO `mydb`.`Eveniment` (`id`, `denumire`, `data`, `durata`, `id_joc`) VALUES (2, 'DarkTwinge Stream Schedule', '25.08.2016', '17 zile', 2);
INSERT INTO `mydb`.`Eveniment` (`id`, `denumire`, `data`, `durata`, `id_joc`) VALUES (3, 'RickDgaming Stream Schedule', '26.08.2016', '11 zile', 3);
INSERT INTO `mydb`.`Eveniment` (`id`, `denumire`, `data`, `durata`, `id_joc`) VALUES (4, 'Minecon Main Stage Stream', '24.09.2016', '2 zile', 4);

COMMIT;

